// <auto-generated />
namespace WebAppStudomat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_users2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_users2));
        
        string IMigrationMetadata.Id
        {
            get { return "202104302248187_added_users2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
