// <auto-generated />
namespace WebAppStudomat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class users4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(users4));
        
        string IMigrationMetadata.Id
        {
            get { return "202104302236152_users4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
